name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # use o output do GitHub actions como entrada do Readme
          output: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
